apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: pgvector/pgvector:pg16
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_USER
          value: "REPLACE_WITH_DB_USER"
        - name: POSTGRES_PASSWORD
          value: "REPLACE_WITH_DB_PASSWORD"
        - name: POSTGRES_DB
          value: "REPLACE_WITH_DB_NAME"
        ports:
        - containerPort: 5432